import { useEffect, useMemo, useState } from "react"
import { Archive, CheckCircle2, Clock3, FolderOpen, History, RotateCcw, ShieldCheck, ShieldAlert, TriangleAlert } from "lucide-react"
import { toast } from "react-toastify"
import RootDiv from "@/components/rootdiv"
import Button from "@/components/ui/button"
import { invoke } from "@/lib/electron"
import { useI18n } from "@/i18n"

export default function SafetyCenter() {
  const { language } = useI18n()
  const [audit,setAudit]=useState<any>(null), [history,setHistory]=useState<any[]>([]), [busy,setBusy]=useState(false)
  const text=useMemo(()=>language==='pt-BR'?{title:'Central de Segurança',sub:'Auditoria, histórico e reversão das alterações executadas pelo Zevyron.',audit:'Auditoria das otimizações',history:'Histórico de alterações',undo:'Desfazer',restore:'Criar ponto de restauração'}:language==='es-ES'?{title:'Centro de Seguridad',sub:'Auditoría, historial y reversión de cambios realizados por Zevyron.',audit:'Auditoría de optimizaciones',history:'Historial de cambios',undo:'Deshacer',restore:'Crear punto de restauración'}:{title:'Safety Center',sub:'Audit, history and rollback for changes performed by Zevyron.',audit:'Optimization audit',history:'Change history',undo:'Undo',restore:'Create restore point'},[language])
  async function load(){const [a,h]=await Promise.all([invoke({channel:'safety:audit'}),invoke({channel:'safety:history'})]);setAudit(a);setHistory(h||[])}
  useEffect(()=>{load().catch(()=>{})},[])
  async function undo(id:string){setBusy(true);try{const r=await invoke({channel:'safety:undo',payload:id});r?.success===false?toast.error(r.error||'Falha ao desfazer'):toast.success('Alteração revertida com o Safety Engine.');await load()}finally{setBusy(false)}}
  async function restore(){setBusy(true);try{const r=await invoke({channel:'create-zevyron-restore-point'});if(r?.success===false)toast.error(r.message||'Falha ao criar ponto de restauração');else toast.success('Ponto de restauração criado.')}finally{setBusy(false)}}
  return <RootDiv><div className="max-w-[1500px] mx-auto p-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="flex gap-2 items-center text-emerald-400 text-xs font-semibold"><ShieldCheck size={16}/> ZEVYRON SAFETY ENGINE</div><h1 className="text-3xl font-bold mt-1">{text.title}</h1><p className="text-sm text-zevyron-text-secondary mt-1">{text.sub}</p></div><div className="flex gap-2"><Button variant="secondary" onClick={()=>invoke({channel:'safety:open-folder'})}><FolderOpen size={16}/> Logs</Button><Button onClick={restore} disabled={busy}><Archive size={16}/>{text.restore}</Button></div></div>
  {audit&&<div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[["Total",audit.total,<History/>,'text-[#1fb6ff]'],["Seguros",audit.safe,<CheckCircle2/>,'text-emerald-400'],["Moderados",audit.moderate,<TriangleAlert/>,'text-amber-400'],["Avançados",audit.advanced,<ShieldAlert/>,'text-red-400'],["Sem reversão",audit.nonReversible,<RotateCcw/>,'text-zevyron-text-secondary']].map(([l,v,i,c]:any)=><div key={l} className="rounded-xl border border-zevyron-border bg-[#071221] p-4"><div className={`flex items-center gap-2 text-xs ${c}`}>{i}{l}</div><div className="text-3xl font-bold mt-2">{v}</div></div>)}</div>}
  <section className="rounded-xl border border-zevyron-border bg-[#071221] p-4"><h2 className="font-semibold mb-3">{text.audit}</h2>{audit?<div className="grid md:grid-cols-3 gap-2 max-h-[300px] overflow-auto pr-1">{audit.tweaks.map((x:any)=><div key={x.name} className="p-3 rounded-lg border border-zevyron-border bg-[#06101d]"><div className="flex items-center justify-between gap-2"><span className="text-sm font-medium truncate">{x.title}</span><span className={`text-[10px] px-2 py-1 rounded-full ${x.level==='safe'?'text-emerald-400 bg-emerald-500/10':x.level==='moderate'?'text-amber-400 bg-amber-500/10':'text-red-400 bg-red-500/10'}`}>{x.level}</span></div><div className="text-[11px] text-zevyron-text-secondary mt-1">{x.reversible?'Reversível':'Sem reversão automática'} · risco {x.score}/100</div></div>)}</div>:<div>Carregando...</div>}</section>
  <section className="rounded-xl border border-zevyron-border bg-[#071221] p-4"><h2 className="font-semibold mb-3">{text.history}</h2><div className="space-y-2">{history.length===0?<div className="text-sm text-zevyron-text-secondary">Nenhuma alteração registrada ainda.</div>:history.slice(0,50).map((h:any)=><div key={h.id} className="p-3 rounded-lg border border-zevyron-border bg-[#06101d] flex flex-wrap items-center gap-3"><span className={h.success?'text-emerald-400':'text-red-400'}>{h.success?<CheckCircle2 size={18}/>:<ShieldAlert size={18}/>}</span><div className="flex-1 min-w-[220px]"><div className="text-sm font-medium">{h.title}</div><div className="text-[11px] text-zevyron-text-secondary flex gap-2"><span>{h.action}</span><span>•</span><span>{h.level}</span><span>•</span><Clock3 size={12}/><span>{new Date(h.finishedAt).toLocaleString()}</span></div></div>{h.success&&h.action==='apply'&&h.reversible&&<Button variant="secondary" disabled={busy} onClick={()=>undo(h.id)}><RotateCcw size={14}/>{text.undo}</Button>}</div>)}</div></section>
  </div></RootDiv>
}
